### ISSUE TITLE
qc_report will only take full path to zipfiles

### ISSUE THREAD

**Issue by ACharbonneau** [kassambara/fastqcr#1]
I'm running fastqrc from the folder that contains all the zip files. 
> qc.path <- "."

Running `list.files(qc.path)` gives files as expected, and `qc <- qc_aggregate(qc.path)` gives a valid report, however `qc_report(qc.path, result.file = "test")` gives:

>Quitting from lines 51-53 (multi-qc-report.Rmd)
Error in qc_aggregate(qc.path, progressbar = FALSE) :
  Can't find any *fastqc.zip files in the specified qc.dir

Replacing the relative path with a full path to the same directory allows both qc_aggregate and qc_report to run, but requiring full paths limits the program's usability for scripting.  This is on an HPC, running R/3.2.0 and pandoc/1.17.3

**Comment by kassambara** [comment]
Hi,

Thank you for pointing this out. 

The following code should work:

```r
qc_report(qc.path = getwd(), result.file = "test")
````

**Comment by kassambara** [comment]
fixed now! Please, install the latest developmental version and let me know if it works now  when using qc.path = "." .

To install:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/fastqcr")
```

**Comment by ACharbonneau** [comment]
Beat me to it. But it doesn't like the getwd solution:

> qc_report(qc.path = getwd(), result.file = "test")
Error in qc_report(qc.path = getwd(), result.file = "test") :
  unused arguments (qc.path = getwd(), result.file = "test")

Pulling the update now.

**Comment by kassambara** [comment]
oh, great! so we can close this issue. Thank you again for pointing this out.

**Comment by kassambara** [comment]
better stable solution to handle relative path added now
