### ISSUE TITLE
Match name error

### ISSUE THREAD

**Issue by palfalvi** [kassambara/fastqcr#10]
Hi!

Thanks for the package! I installed and started to use with 200+ samples. I could run `fastqc()`, I can see and browse the outputs from cmd, but `qc_aggregate()` gives the following error:

```
fastqcr::qc_aggregate("fastqc/", progressbar = FALSE)
```
```
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
```

Same with the example data. Since i cannot get a qc_aggregate class object, no downstream function works. 

`qc_report()` throws back the following:

```
fastqcr::qc_report("fastqc/", result.file = "multi-qc-report")
```
```
Quitting from lines 51-53 (multi-qc-report.Rmd) 
Error in qc_aggregate(qc.path, progressbar = FALSE) : 
  Can't find any *fastqc.zip files in the specified qc.dir
```

But there are more then 200 files named `*fastqc.zip` in that directory.

So I just can't use any of the cool function of the package. Do you have any idea to fix this?

Thanks in advance!

---

```
>devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Tokyo                  
 date     2018-08-23             
```

**Comment by kassambara** [comment]
I’m far from the computer. I will be able to check that next week.

Please, provide the complete output of devtools:session_infos()

**Comment by palfalvi** [comment]
Thanks for the fast reply, no problem.

Session info -------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.419)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Tokyo                  
 date     2018-08-23                  

Packages -----------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                           
 assertthat   0.2.0      2017-04-11 CRAN (R 3.5.0)                   
 backports    1.1.2      2017-12-13 CRAN (R 3.5.0)                   
 base       * 3.5.0      2018-05-14 local                            
 bindr        0.1.1      2018-03-13 CRAN (R 3.5.0)                   
 bindrcpp   * 0.2.2      2018-03-29 CRAN (R 3.5.0)                   
 broom        0.4.5.9000 2018-07-11 Github (tidyverse/broom@05a4889) 
 cellranger   1.1.0      2016-07-27 CRAN (R 3.5.0)                   
 cli          1.0.0      2017-11-05 CRAN (R 3.5.0)                   
 colorspace   1.3-2      2016-12-14 CRAN (R 3.5.0)                   
 compiler     3.5.0      2018-05-14 local                            
 crayon       1.3.4      2017-09-16 CRAN (R 3.5.0)                   
 datasets   * 3.5.0      2018-05-14 local                            
 devtools     1.13.5     2018-02-18 CRAN (R 3.5.0)                   
 digest       0.6.15     2018-01-28 CRAN (R 3.5.0)                   
 dplyr      * 0.7.5      2018-05-19 CRAN (R 3.5.0)                   
 evaluate     0.10.1     2017-06-24 CRAN (R 3.5.0)                   
 fastqcr    * 0.1.0      2017-04-11 CRAN (R 3.5.0)                   
 forcats    * 0.3.0      2018-02-19 CRAN (R 3.5.0)                   
 ggplot2    * 3.0.0      2018-07-03 CRAN (R 3.5.0)                   
 glue         1.3.0      2018-07-17 CRAN (R 3.5.0)                   
 graphics   * 3.5.0      2018-05-14 local                            
 grDevices  * 3.5.0      2018-05-14 local                            
 grid         3.5.0      2018-05-14 local                            
 gtable       0.2.0      2016-02-26 CRAN (R 3.5.0)                   
 haven        1.1.1      2018-01-18 CRAN (R 3.5.0)                   
 hms          0.4.2.9001 2018-08-22 Github (tidyverse/hms@979286f)   
 httr         1.3.1      2017-08-20 CRAN (R 3.5.0)                   
 jsonlite     1.5        2017-06-01 CRAN (R 3.5.0)                   
 knitr        1.20       2018-02-20 CRAN (R 3.5.0)                   
 lattice      0.20-35    2017-03-25 CRAN (R 3.5.0)                   
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.5.0)                   
 lubridate    1.7.4      2018-04-11 CRAN (R 3.5.0)                   
 magrittr     1.5        2014-11-22 CRAN (R 3.5.0)                   
 memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)                   
 methods    * 3.5.0      2018-05-14 local                            
 modelr       0.1.2.9000 2018-06-21 Github (tidyverse/modelr@28c55db)
 munsell      0.5.0      2018-06-12 CRAN (R 3.5.0)                   
 nlme         3.1-137    2018-04-07 CRAN (R 3.5.0)                   
 pillar       1.3.0      2018-07-14 CRAN (R 3.5.0)                   
 pkgconfig    2.0.2      2018-08-16 cran (@2.0.2)                    
 plyr         1.8.4      2016-06-08 CRAN (R 3.5.0)                   
 purrr      * 0.2.5      2018-05-29 CRAN (R 3.5.0)                   
 R6           2.2.2      2017-06-17 CRAN (R 3.5.0)                   
 Rcpp         0.12.17    2018-05-18 CRAN (R 3.5.0)                   
 readr      * 1.2.0      2018-06-21 Github (tidyverse/readr@05890c3) 
 readxl       1.1.0      2018-04-20 CRAN (R 3.5.0)                   
 reshape2     1.4.3      2017-12-11 cran (@1.4.3)                    
 rlang        0.2.2      2018-08-16 cran (@0.2.2)                    
 rstudioapi   0.7        2017-09-07 CRAN (R 3.5.0)                   
 rvest        0.3.2      2016-06-17 CRAN (R 3.5.0)                   
 scales       0.5.0.9000 2018-06-21 Github (hadley/scales@80fe94c)   
 stats      * 3.5.0      2018-05-14 local                            
 stringi      1.2.3      2018-06-12 CRAN (R 3.5.0)                   
 stringr    * 1.3.1      2018-05-10 CRAN (R 3.5.0)                   
 tibble     * 1.4.2      2018-01-22 CRAN (R 3.5.0)                   
 tidyr      * 0.8.1      2018-05-18 CRAN (R 3.5.0)                   
 tidyselect   0.2.4      2018-02-26 CRAN (R 3.5.0)                   
 tidyverse  * 1.2.1      2017-11-14 CRAN (R 3.5.0)                   
 tools        3.5.0      2018-05-14 local                            
 utils      * 3.5.0      2018-05-14 local                            
 withr        2.1.2      2018-03-15 CRAN (R 3.5.0)                   
 xml2         1.2.0      2018-01-24 CRAN (R 3.5.0)                   
 yaml         2.1.19     2018-05-01 CRAN (R 3.5.0)

**Comment by osowiecki** [comment]
Any news? It dosn't work for me in any version of R (3.3-3.5).

**Comment by valscherz** [comment]
Same here…

**Comment by osowiecki** [comment]
Hey! Install it from Anaconda bioconda first and don't update packages later. Make a separate environment. It works that way.

**Comment by nash-claire** [comment]
I have this same error on a fresh install of Ubuntu Bionic Beaver, a fresh install of R, devtools and fastqcr. I'd rather avoid installing and using Bioconda etc. Is there another way to fix the issue?

**Comment by nash-claire** [comment]
Thanks for the reply osowiecki, I appreciate it. So I went through and installed all the same versions of the dependencies that you sent to me. There were 2 I couldn't change, grid and compiler. And sure enough, when I tried to run fastqcr again, I still get the same error. Can you confirm osowiecki which version of R you are running? compiler is built in to the R version I'm using so I don't think I can change it. Grid is also not available for my version of R.

**Comment by osowiecki** [comment]
> Thanks for the reply osowiecki, I appreciate it. So I went through and installed all the same versions of the dependencies that you sent to me. There were 2 I couldn't change, grid and compiler. And sure enough, when I tried to run fastqcr again, I still get the same error. Can you confirm osowiecki which version of R you are running? compiler is built in to the R version I'm using so I don't think I can change it. Grid is also not available for my version of R.

R version 3.5.1 (2018-07-02) -- "Feather Spray"

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fastqcr_0.1.0

Install fastqcr via conda in a virtual environment. Activate this R environment for fastqcr and use it. Here is more info on how to do it.

http://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language/
https://stackoverflow.com/questions/24283171/virtual-environment-in-r

**Comment by kassambara** [comment]
Installing the latest developmental version should now fix this issue.

```r
devtools::install_github("kassambara/fastqcr")
````

Please , let me know, thanks!

**Comment by osowiecki** [comment]
> ```r
> devtools::install_github("kassambara/fastqcr")
> ```

17 parsing failures.
row # A tibble: 5 x 5 col     row col   expected  actual    file         expected   <int> <chr> <chr>     <chr>     <chr>        actual 1     1 NA    2 columns 3 columns literal data file 2     2 NA    2 columns 3 columns literal data row 3     3 NA    2 columns 3 columns literal data col 4     4 NA    2 columns 3 columns literal data expected 5     5 NA    2 columns 3 columns literal data
... ................................. ... .............................................. ........ ........................................................................................................................................................................... ...... ......................................  [... truncated]
in command '.f(.x[[i]], ...)':object not found 'module'



43: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)

**Comment by osowiecki** [comment]
OK. Updating all packages seems to fix the issue with new version of fastqcr

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /home/debian/miniconda3/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pl_PL.UTF-8        LC_COLLATE=pl_PL.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2 fastqcr_0.1.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       bindr_0.1.1      magrittr_1.5     hms_0.4.2       
 [5] tidyselect_0.2.5 munsell_0.5.0    colorspace_1.3-2 R6_2.3.0        
 [9] rlang_0.3.0.1    fansi_0.4.0      plyr_1.8.4       dplyr_0.7.8     
[13] grid_3.5.1       gtable_0.2.0     utf8_1.1.4       cli_1.0.0       
[17] lazyeval_0.2.1   assertthat_0.2.0 tibble_1.4.2     crayon_1.3.4    
[21] purrr_0.2.5      readr_1.2.1      ggplot2_3.1.0    glue_1.3.0      
[25] compiler_3.5.1   pillar_1.3.0     scales_1.0.0     pkgconfig_2.0.2

**Comment by kassambara** [comment]
so we can close this issue, thanks

**Comment by lida-R** [comment]
Hello, 

I had the same issue and based on your suggestion, we updated to the newer version and that error is gone and I was able to generate the qc metrics but some of the modules are NA while it worked with previous version with same data! Do you have any thoughts?
Thank you.
qc$tot.seq
  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [47] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [93] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
qcstat<- qc_stats(qc)
> qcstat
   sample    pct.dup  pct.gc  tot.seq  seq.length
   <chr>       <dbl>  <dbl> <chr>   <chr>     
 1 C_rep1_R1    72.4     NA NA      NA        
 2 C_rep1_R2    72.8     NA NA      NA        
 3 C_rep2_R1    72.8     NA NA      NA        
 4 C_rep2_R2    72.8     NA NA      NA        
 5 C_rep3_R1    71.6     NA NA      NA        
 6 C_rep3_R2    70.8     NA NA      NA        
 7 P_rep1_R1    69.1     NA NA      NA        
 8 P_rep1_R2    67.9     NA NA      NA        
 9 P_rep2_R1    68.6     NA NA      NA        
10 P_rep2_R2    67.4     NA NA      NA        
11 P_rep3_R1    72.3     NA NA      NA        
12 P_rep3_R2    71.3     NA NA      NA
