### ISSUE TITLE
getting NA in some modules of qc.aggregation function in new version (0.1.1)

### ISSUE THREAD

**Issue by lida-R** [kassambara/fastqcr#12]
Hello,

I had the same issue with https://github.com/kassambara/fastqcr/issues/10 and based on your suggestion, updated to the newer version (0.1.1) and that error is gone and I was able to generate the qc metrics but some of the modules are NA while it worked with previous version (0.1.0) with same data! Do you have any thoughts?
Thank you.
qc$tot.seq
[1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[47] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[93] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
qcstat<- qc_stats(qc)

qcstat
sample pct.dup pct.gc tot.seq seq.length

1 C_rep1_R1 72.4 NA NA NA
2 C_rep1_R2 72.8 NA NA NA
3 C_rep2_R1 72.8 NA NA NA
4 C_rep2_R2 72.8 NA NA NA
5 C_rep3_R1 71.6 NA NA NA
6 C_rep3_R2 70.8 NA NA NA
7 P_rep1_R1 69.1 NA NA NA
8 P_rep1_R2 67.9 NA NA NA
9 P_rep2_R1 68.6 NA NA NA
10 P_rep2_R2 67.4 NA NA NA
11 P_rep3_R1 72.3 NA NA NA
12 P_rep3_R2 71.3 NA NA NA

**Comment by kassambara** [comment]
Fixed by the pull request https://github.com/kassambara/fastqcr/pull/11.

Please, install the latest developmental version of fastqcr and let me know if it works. readr 1.3 required.

```r
devtools::install_github("kassambara/fastqcr")
```

**Comment by cauwerx** [comment]
Yes it worked! Thanks a lot!

**Comment by lida-R** [comment]
Thank you Kassambara, It worked for me too.

**Comment by kassambara** [comment]
thanks, so we can close this issue
