### ISSUE TITLE
`select()` instead of select_()`in qc_aggregate.R

### ISSUE THREAD

**Issue by Elizaddh** [kassambara/fastqcr#24]
Hi,

While running the qc_aggregate, I get an warning message saying that 

1: `select_()` was deprecated in dplyr 0.7.0.
ℹ Please use `select()` instead.
ℹ The deprecated feature was likely used in the fastqcr package.
  Please report the issue at <https://github.com/kassambara/fastqcr/issues>.

It would be great if you can update this in line 85 of qc_aggregate.R or any other line that is generating the warning message.

Thank you.

Sincerely,
Eliza Dhungel

**Comment by kassambara** [comment]
fixed now, thanks
