### ISSUE TITLE
Overlaying plots ?

### ISSUE THREAD

**Issue by SiddharthTomar** [kassambara/fastqcr#3]
Nice package! I was wondering if it is possible to overlay the qc plots, i.e. probably before and after reads are "cleaned", for a straight forward comparative analysis.
Another issue is that I have to use the development branch of ggplot2 just to use this package, which can be little troublesome.

**Comment by kassambara** [comment]
I'll work on that.

regarding ggplot2, I have  CRAN version 2.2.1 on my computer and it works with fastqcr.

**Comment by MahShaaban** [comment]
I made some suggestions to extend the **fastqcr** code to import multiple files and make overlaying plots #4

**Comment by kassambara** [comment]
NEWS updated, thanks.

I think that we can now close this issue.
