### ISSUE TITLE
sh: 1: fastqc: not found

### ISSUE THREAD

**Issue by PamelaMehanna** [kassambara/fastqcr#8]
Hi,

I successfully installed the fastqcr package on R/3.3.3, both locally and on a cluster.
I load the library and then when I try to use the first command:
fastqc(fq.dir = "/home/user/test_fastq", qc.dir = "/home/user/test_fastq/fastqc", threads = 4)
it outputs this error immediately:
sh: 1: fastqc: not found

What am I doing wrong?
I tried doing fastqc_install(), but that didn't change anything..

Thank you for your help.

**Comment by s18692001** [comment]
I have the same problem. Do you solve it? Thanks!

Simon
