### ISSUE TITLE
sh: 1: fastqc: not found

### ISSUE THREAD

**Issue by s18692001** [kassambara/fastqcr#9]
Hi there,

I installed the fastqcr package on R 3.4.4 locally.
I run the command fastqc_install() successfully and tried:
fastqc(fq.dir = "/home/user/test_fastq", qc.dir = "/home/user/fastqc", threads = 1)
but I got the following error:
sh: 1: fastqc: not found

What should I do? Thanks!

Simnon

**Comment by palfalvi** [comment]
Try to move fastqc to /bin/ or ~/bin/ or add the installation directory to your $PATH.
